version: '3'

services:
  traefik:
    image: traefik:v2.7
    container_name: traefik
    network_mode: bridge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=${URL}
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.tls=true
