version: "2.1"
services:
  rutorrent:
    image: ghcr.io/linuxserver/rutorrent
    container_name: rutorrent
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.http.routers.rutorrent.rule=${HOST}
      - traefik.http.routers.rutorrent.entrypoints=websecure
      - traefik.http.routers.rutorrent.tls=true
    volumes:
      - ${DIR}/config:/config
      - ${STORAGE}/downloads:/downloads
    ports:
      # - 80:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
