version: '3'

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    network_mode: "bridge"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8090:8080"  # Don't do this in production!
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
# networks:
#   default:
#     external:
#       name: bridge