version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-TUWWzxJ8xkNAwceQeaz8
      - ADVERTISE_IP=https://plex.beteiro.app/
    volumes:
      - ./plex_library:/config
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    labels:
      - traefik.enable=true
      # - traefik.docker.network=traefik_public
      - traefik.http.routers.plex.rule=Host(`plex.beteiro.app`)
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.tls=true
    restart: unless-stopped
# networks:
#   default:
#     external:
#       name: traefik_default