version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM_KEY}
      - ADVERTISE_IP=${ADVERTISE_URL}
    volumes:
      - ./plex_library:/config
      - ${STORAGE}/politec:/politec
      - ${STORAGE}/downloads:/downloads
      - ${STORAGE}/cursos:/cursos
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=${HOST_PLEX}
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.tls=true
    restart: unless-stopped
