version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: metro
    container_name: metro-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist
  nginx:
    image: nginx:alpine
    container_name: metro-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./:/etc/nginx/conf.d/
    networks:
      - travellist

networks:
  travellist:
    driver: bridge